### ISSUE TITLE
f1 metric for `query_named_entity_recognition_new` task

### ISSUE THREAD

**Issue by mistycheney** [KL4805/ShoppingMMLU#1]
Thanks for this awesome benchmark! It's a great gift for the community.

I just have a question regarding the f1 metric for the `query_named_entity_recognition_new` task. My intuition is we should compute an f-1 score for each sample, and then average them to get the task-wise score. However in the code [here](https://github.com/KL4805/ShoppingMMLU/blob/main/skill_wise_eval/skill_evaluation.py#L125), the task-wise score is the f-1 computed across all samples. What is the rationale for this calculation, and why is this preferred over the former more intuitive method? Thank you

**Comment by KL4805** [comment]
Hi, thank you for your interest in our work! 

According to this [paper](https://ieeexplore.ieee.org/abstract/document/9039685/), the TP, FP, FN, etc. are first evaluated over the whole corpus, before calculating the F1 score.

**Comment by mistycheney** [comment]
Got it. Thanks for the pointer and explanation.
